version: '3.8'
services:
  web:
    build: ./bitcoin-price-nuxt-app/
    ports:
      - "3000:3000"
    depends_on:
      - db

  back:
    build: ./bitcoin-price-nuxt-app/server/
    ports:
      - "3001:3001"
    depends_on:
      - db

  service:
    build: ./service/
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=my_postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
